--INSERT INTO estilo(descricao,url,ativo) VALUES('Twitter Bootstrap','/webresources/twitter-bootstrap/css/bootstrap.css',true);
INSERT INTO estilo(descricao,url,ativo) VALUES('Amelia','/webresources/twitter-bootstrap/css/bootstrap-amelia.css',true);
INSERT INTO estilo(descricao,url,ativo) VALUES('Cerulean','/webresources/twitter-bootstrap/css/bootstrap-cerulean.css',true);
INSERT INTO estilo(descricao,url,ativo) VALUES('Cyborg','/webresources/twitter-bootstrap/css/bootstrap-cyborg.css',true);
INSERT INTO estilo(descricao,url,ativo) VALUES('Readable','/webresources/twitter-bootstrap/css/bootstrap-readable.css',true);
INSERT INTO estilo(descricao,url,ativo) VALUES('Responsive','/webresources/twitter-bootstrap/css/bootstrap-responsive.css',true);
INSERT INTO estilo(descricao,url,ativo) VALUES('Simplex','/webresources/twitter-bootstrap/css/bootstrap-simplex.css',true);
INSERT INTO estilo(descricao,url,ativo) VALUES('Slate','/webresources/twitter-bootstrap/css/bootstrap-slate.css',true);
INSERT INTO estilo(descricao,url,ativo) VALUES('Spacelab','/webresources/twitter-bootstrap/css/bootstrap-spacelab.css',true);
INSERT INTO estilo(descricao,url,ativo) VALUES('Spruce','/webresources/twitter-bootstrap/css/bootstrap-spruce.css',true);
INSERT INTO estilo(descricao,url,ativo) VALUES('Superhero','/webresources/twitter-bootstrap/css/bootstrap-superhero.css',true);
INSERT INTO estilo(descricao,url,ativo) VALUES('United','/webresources/twitter-bootstrap/css/bootstrap-united.css',true);